/* Bloom local prototype: replaceable modules around a small domain core. */
(() => {
  'use strict';

  const MODULES = [
    {id:'home',label:'Overview',icon:'⌂',roles:['customer','partner','admin']},
    {id:'discover',label:'Discover services',icon:'✦',roles:['customer']},
    {id:'bookings',label:'My bookings',icon:'▣',roles:['customer','partner']},
    {id:'partners',label:'Partners',icon:'♧',roles:['partner','admin']},
    {id:'operations',label:'Operations',icon:'◈',roles:['admin']},
    {id:'inventory',label:'Inventory kits',icon:'◇',roles:['partner','admin']},
    {id:'support',label:'Support & SOS',icon:'♡',roles:['customer','partner','admin']}
  ];
  const SERVICES = [
    {id:'s1',name:'Bloom signature facial',category:'Skin',duration:'60 min',price:1200,art:'✺',description:'A calming, glow-focused facial with a botanical finish.'},
    {id:'s2',name:'Blow dry & styling',category:'Hair',duration:'45 min',price:850,art:'⌁',description:'Salon-fresh volume and shape, brought to your doorstep.'},
    {id:'s3',name:'Gel manicure',category:'Nails',duration:'60 min',price:950,art:'✿',description:'Long-wear colour, cuticle care, and a neat finish.'},
    {id:'s4',name:'Relaxation massage',category:'Wellness',duration:'75 min',price:1600,art:'☼',description:'A tailored full-body session to reset your week.'},
    {id:'s5',name:'Bridal glow ritual',category:'Packages',duration:'120 min',price:2800,art:'✧',description:'A complete pre-event ritual for skin, hair, and calm.'},
    {id:'s6',name:'Express pedicure',category:'Nails',duration:'40 min',price:700,art:'◌',description:'A fresh, polished reset for busy days.'}
  ];
  const SEED = {role:'customer',view:'home',address:'Home · 14 Green Park',bookings:[
    {id:'BL-1042',service:'Bloom signature facial',date:'2026-09-19',time:'10:30 AM',partner:'Anika Rao',status:'Confirmed',price:1200,address:'Home · 14 Green Park'},
    {id:'BL-1038',service:'Blow dry & styling',date:'2026-09-12',time:'4:00 PM',partner:'Meera Kapoor',status:'Completed',price:850,address:'Home · 14 Green Park'}
  ]};

  // Storage adapter: this is the only module that knows localStorage exists.
  const repository = {
    load() { try { return {...SEED,...JSON.parse(localStorage.getItem('bloom-state') || '{}')}; } catch { return {...SEED}; } },
    save(state) { localStorage.setItem('bloom-state', JSON.stringify(state)); },
    reset() { localStorage.removeItem('bloom-state'); return this.load(); }
  };
  let state = repository.load();
  const $ = (selector, root=document) => root.querySelector(selector);
  const money = value => `₹${Number(value).toLocaleString('en-IN')}`;
  const dateParts = date => { const d = new Date(`${date}T12:00:00`); return {day:d.getDate(),month:d.toLocaleString('en-US',{month:'short'}),full:d.toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric'})}; };
  const currentModule = () => MODULES.find(m => m.id === state.view) || MODULES[0];
  const setState = patch => { state={...state,...patch}; repository.save(state); render(); };
  const notify = message => { const toast=$('#toast'); toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2600); };

  const navMarkup = () => MODULES.filter(m=>m.roles.includes(state.role)).map(m=>`<button class="nav-item ${m.id===state.view?'active':''}" data-view="${m.id}"><span class="nav-icon">${m.icon}</span>${m.label}</button>`).join('');
  const headerMarkup = () => `<span>Bloom workspace</span> <span> / </span> <b>${currentModule().label}</b>`;
  const status = value => `<span class="status ${value.toLowerCase()==='pending'?'pending':''} ${value.toLowerCase()==='cancelled'?'cancelled':''}">${value}</span>`;

  function bookingRow(booking, compact=false) { const d=dateParts(booking.date); return `<div class="booking-row"><div class="date-tile"><b>${d.day}</b><small>${d.month}</small></div><div><h3>${booking.service}</h3><p>${booking.time} · ${booking.partner} · ${booking.address}</p></div>${status(booking.status)}${compact?'':`<button class="btn btn-quiet" data-booking="${booking.id}">View details</button>`}</div>`; }
  function pageHead(kicker,title,description,action='') { return `<div class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>${action?`<div class="actions">${action}</div>`:''}</div>`; }
  function home() { const upcoming=state.bookings.find(b=>b.status==='Confirmed'); return `${pageHead('Saturday, 19 September','Good morning, Riya.','Your personal care plan, in one calm place.',`<button class="btn btn-primary" data-action="new-booking">＋ Book a service</button>`)}<div class="dashboard-grid"><div class="card hero-card"><div><span class="eyebrow">Your next moment</span><h2>${upcoming?'A little time, just for you.':'Make space for yourself.'}</h2><p>${upcoming?`${upcoming.service} is booked for ${dateParts(upcoming.date).full}.`:'Discover trusted professionals who come to you.'}</p></div><button class="btn btn-secondary" style="width:max-content" data-view="${upcoming?'bookings':'discover'}">${upcoming?'View booking':'Explore services'} →</button></div><div class="card metric"><span class="eyebrow">This month</span><span class="number">${state.bookings.filter(b=>b.status!=='Cancelled').length}</span><small>care moments booked</small></div><div class="card metric"><span class="eyebrow">Bloom balance</span><span class="number">₹450</span><small>available rewards</small></div></div><div class="section-heading"><h2>Upcoming visits</h2><button class="link" data-view="bookings">See all bookings →</button></div><div class="booking-list">${upcoming?bookingRow(upcoming):'<div class="empty">No upcoming visits yet. Your next reset is one click away.</div>'}</div><div class="section-heading"><h2>Made for your rhythm</h2></div><div class="quick-grid"><div class="quick-card"><span>✧</span><b>Glow & skin</b><small class="muted">Facials and rituals</small></div><div class="quick-card"><span>⌁</span><b>Hair at home</b><small class="muted">Style without travel</small></div><div class="quick-card"><span>☼</span><b>Wellness</b><small class="muted">Feel restored</small></div><div class="quick-card"><span>♡</span><b>Need help?</b><small class="muted">We are here for you</small></div></div>`; }
  function discover() { return `${pageHead('The Bloom edit','Find your next ritual','Thoughtful services from trained, verified professionals — wherever you are.',`<button class="btn btn-secondary" data-action="address">⌖ ${state.address}</button>`)}<div class="catalog-toolbar"><input class="search" id="serviceSearch" placeholder="Search services..." /><select class="filter" id="serviceFilter"><option>All categories</option>${[...new Set(SERVICES.map(s=>s.category))].map(c=>`<option>${c}</option>`).join('')}</select></div><div id="serviceGrid" class="service-grid">${serviceCards(SERVICES)}</div>`; }
  function serviceCards(list) { return list.map(s=>`<article class="service-card"><div class="service-art">${s.art}</div><div class="service-body"><span class="eyebrow">${s.category} · ${s.duration}</span><h3>${s.name}</h3><p>${s.description}</p><div class="service-meta"><span class="price">${money(s.price)}</span><button class="btn btn-primary" data-book-service="${s.id}">Book</button></div></div></article>`).join('') || '<div class="empty">No services match that search.</div>'; }
  function bookings() { return `${pageHead('Your care plan','My bookings','Keep every appointment, update the details, and follow your professional in real time.',`<button class="btn btn-primary" data-action="new-booking">＋ New booking</button>`)}<div class="booking-list">${state.bookings.map(b=>bookingRow(b)).join('')}</div>`; }
  function partners() { const people=[['Anika Rao','Skin & wellness','Available today','92%'],['Meera Kapoor','Hair & styling','On a visit','84%'],['Kavya Menon','Nails & beauty','Available today','97%']]; return `${pageHead('Partner network','Professionals','A live view of partner readiness, quality, and capacity.',`<button class="btn btn-primary" data-action="add-partner">＋ Add partner</button>`)}<div class="card"><table class="data-table"><thead><tr><th>Partner</th><th>Speciality</th><th>Availability</th><th>Quality score</th></tr></thead><tbody>${people.map(p=>`<tr><td><b>${p[0]}</b></td><td>${p[1]}</td><td>${status(p[2])}</td><td><b>${p[3]}</b><div class="progress"><span style="width:${p[3]}"></span></div></td></tr>`).join('')}</tbody></table></div>`; }
  function operations() { return `${pageHead('Control room','Operations overview','A single, calm view of bookings, partner supply, and the customer promise.',`<button class="btn btn-secondary" data-action="export">Export report</button>`)}<div class="dashboard-grid"><div class="card metric"><span class="eyebrow">Today’s bookings</span><span class="number">24</span><small>↑ 12% from last Saturday</small></div><div class="card metric"><span class="eyebrow">Fulfilment rate</span><span class="number">96%</span><small>within promised slot</small></div><div class="card metric"><span class="eyebrow">Open support</span><span class="number">06</span><small>2 need attention</small></div></div><div class="section-heading"><h2>Platform modules</h2><span class="muted">Replaceable adapters · local demo</span></div><div class="card"><table class="data-table"><tbody>${[['Booking & scheduling','Healthy','Slot engine and dispatch'],['Payments & wallet','Mocked','Ready for provider adapter'],['Notifications','Mocked','Email / SMS / WhatsApp port'],['Identity & access','Local','Role-aware demo session']].map(x=>`<tr><td><b>${x[0]}</b><br><small class="muted">${x[2]}</small></td><td>${status(x[1])}</td><td><button class="link" data-action="module-info">Configure →</button></td></tr>`).join('')}</tbody></table></div>`; }
  function inventory() { return `${pageHead('Supply & readiness','Inventory kits','Consumables stay close to the professional who needs them.',`<button class="btn btn-primary" data-action="new-kit">＋ Add kit</button>`)}<div class="card"><table class="data-table"><thead><tr><th>Kit / SKU</th><th>Available</th><th>Reorder point</th><th>Health</th></tr></thead><tbody>${[['Facial essentials · SK-001','48','20','Healthy'],['Gel colour set · NT-044','12','15','Reorder'],['Massage oils · WL-008','31','10','Healthy']].map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]} units</td><td>${x[2]} units</td><td>${status(x[3])}</td></tr>`).join('')}</tbody></table></div>`; }
  function support() { return `${pageHead('We have you','Support & SOS','Questions, reschedules, and urgent help should never feel complicated.') }<div class="two-col"><div class="card"><span class="eyebrow">Quick help</span><h2 style="font:27px Georgia,serif">How can we help today?</h2><div class="quick-grid" style="grid-template-columns:1fr 1fr;margin-top:20px"><button class="quick-card" data-action="support"><span>◌</span><b>Chat with Bloom</b></button><button class="quick-card" data-action="reschedule"><span>↻</span><b>Reschedule a visit</b></button><button class="quick-card" data-action="support"><span>?</span><b>FAQs</b></button><button class="quick-card" data-action="sos"><span>!</span><b>Emergency SOS</b></button></div></div><div class="card"><span class="eyebrow">Recent conversation</span><h3>Welcome to Bloom support</h3><p class="muted">Our local demo keeps this channel ready for a real messaging adapter.</p><button class="btn btn-secondary" data-action="support">Start a conversation</button></div></div>`; }
  const views={home,discover,bookings,partners,operations,inventory,support};
  function render() { const viewFn=views[state.view]||home; if(!MODULES.find(m=>m.id===state.view&&m.roles.includes(state.role))) state.view='home'; $('#nav').innerHTML=navMarkup(); $('#breadcrumb').innerHTML=headerMarkup(); $('#roleSwitcher').innerHTML=`<span>${state.role==='customer'?'Customer view':state.role==='partner'?'Partner studio':'Admin control room'}</span><span>⌄</span>`; $('#content').innerHTML=viewFn(); bind(); }
  function bind() { document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>setState({view:el.dataset.view})); document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action)); document.querySelectorAll('[data-book-service]').forEach(el=>el.onclick=()=>openBooking(el.dataset.bookService)); document.querySelectorAll('[data-booking]').forEach(el=>el.onclick=()=>openBookingDetails(el.dataset.booking)); const search=$('#serviceSearch'),filter=$('#serviceFilter'); if(search) { const update=()=>{const q=search.value.toLowerCase(),f=filter.value;$('#serviceGrid').innerHTML=serviceCards(SERVICES.filter(s=>(s.name+s.description).toLowerCase().includes(q)&&(f==='All categories'||s.category===f))); bind();}; search.oninput=update;filter.onchange=update; } }
  function action(name) { if(name==='new-booking') setState({view:'discover'}); else if(name==='address') openAddress(); else if(name==='profile') openProfile(); else if(name==='notifications') notify('You are all caught up.'); else if(name==='support') notify('Support channel opened — this demo is ready for a real adapter.'); else if(name==='sos') notify('SOS flow prepared. In production this connects to local emergency support.'); else if(name==='reschedule') notify('Select a booking to reschedule.'); else if(name==='export') notify('Report exported to your browser downloads.'); else if(name==='add-partner'||name==='new-kit'||name==='module-info') notify('Configuration module is ready to be connected.'); }
  function modal(body) { $('#modal-root').innerHTML=`<div class="modal-backdrop" data-close><section class="modal" onclick="event.stopPropagation()">${body}</section></div>`; $('.modal-backdrop').onclick=()=>$('#modal-root').innerHTML=''; }
  function openBooking(serviceId) { const service=SERVICES.find(s=>s.id===serviceId)||SERVICES[0]; modal(`<div class="modal-head"><div><span class="eyebrow">New Bloom visit</span><h2>${service.name}</h2></div><button class="close" data-close>×</button></div><p>${service.duration} · ${money(service.price)} · ${state.address}</p><form id="bookingForm" class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" value="2026-09-19" required></div><div class="field"><label>Preferred slot</label><select name="time"><option>10:30 AM</option><option>1:00 PM</option><option>4:00 PM</option><option>6:30 PM</option></select></div><div class="field"><label>Professional preference</label><select name="partner"><option>Best available Bloom professional</option><option>Anika Rao</option><option>Meera Kapoor</option></select></div><button class="btn btn-primary" type="submit">Confirm booking · ${money(service.price)}</button></form>`); $('#bookingForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.bookings.unshift({id:'BL-'+Math.floor(1000+Math.random()*8999),service:service.name,date:f.get('date'),time:f.get('time'),partner:f.get('partner'),status:'Confirmed',price:service.price,address:state.address});repository.save(state);$('#modal-root').innerHTML='';state.view='bookings';render();notify('Your Bloom visit is confirmed.');}; }
  function openBookingDetails(id) { const b=state.bookings.find(x=>x.id===id); if(!b)return; modal(`<div class="modal-head"><div><span class="eyebrow">${b.id} · ${b.status}</span><h2>${b.service}</h2></div><button class="close" data-close>×</button></div><p>${dateParts(b.date).full} · ${b.time}<br>${b.partner} · ${b.address}</p><div class="timeline"><div class="timeline-item done"><span class="dot"></span><div><strong>Booking confirmed</strong><small>Your professional has accepted the visit.</small></div></div><div class="timeline-item done"><span class="dot"></span><div><strong>Kit prepared</strong><small>Everything needed for your ritual is ready.</small></div></div><div class="timeline-item"><span class="dot"></span><div><strong>On the way</strong><small>Live tracking becomes available on visit day.</small></div></div></div><button class="btn btn-secondary" data-action="reschedule">Reschedule or cancel</button>`); }
  function openAddress() { modal(`<div class="modal-head"><div><span class="eyebrow">Your places</span><h2>Where should Bloom come?</h2></div><button class="close" data-close>×</button></div><div class="form-grid"><button class="btn btn-secondary" data-set-address="Home · 14 Green Park">⌂ Home · 14 Green Park</button><button class="btn btn-secondary" data-set-address="Studio · 8 River Lane">＋ Add another address</button></div>`); document.querySelectorAll('[data-set-address]').forEach(x=>x.onclick=()=>{state.address=x.dataset.setAddress;repository.save(state);$('#modal-root').innerHTML='';render();notify('Location updated.');}); }
  function openProfile() { modal(`<div class="modal-head"><div><span class="eyebrow">Account</span><h2>Riya Sharma</h2></div><button class="close" data-close>×</button></div><p>Personal account · Bloom rewards member</p><button class="btn btn-secondary" id="resetDemo">Reset demo data</button>`); $('#resetDemo').onclick=()=>{state=repository.reset();$('#modal-root').innerHTML='';render();notify('Demo data restored.');}; }
  $('#roleSwitcher').onclick=()=>{const roles=['customer','partner','admin'],next=roles[(roles.indexOf(state.role)+1)%roles.length];setState({role:next,view:'home'});notify(`${next[0].toUpperCase()+next.slice(1)} workspace selected.`);};
  render();
})();
